#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: autogen
# autospec version: v21
# autospec commit: 0698adb
#
%define keepstatic 1
Name     : colm
Version  : 0.14.7
Release  : 4
URL      : https://github.com/adrian-thurston/colm/archive/refs/tags/0.14.7.tar.gz
Source0  : https://github.com/adrian-thurston/colm/archive/refs/tags/0.14.7.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: colm-bin = %{version}-%{release}
Requires: colm-data = %{version}-%{release}
Requires: colm-license = %{version}-%{release}
BuildRequires : asciidoc
BuildRequires : file
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: backport-add-extern.patch

%description
Colm.Net Suite of Programs
==========================
This package contains the Colm Programming Language, Ragel State Machine
Compiler 7.0+, and supporting libraries.

%package bin
Summary: bin components for the colm package.
Group: Binaries
Requires: colm-data = %{version}-%{release}
Requires: colm-license = %{version}-%{release}

%description bin
bin components for the colm package.


%package data
Summary: data components for the colm package.
Group: Data

%description data
data components for the colm package.


%package dev
Summary: dev components for the colm package.
Group: Development
Requires: colm-bin = %{version}-%{release}
Requires: colm-data = %{version}-%{release}
Provides: colm-devel = %{version}-%{release}
Requires: colm = %{version}-%{release}

%description dev
dev components for the colm package.


%package doc
Summary: doc components for the colm package.
Group: Documentation

%description doc
doc components for the colm package.


%package license
Summary: license components for the colm package.
Group: Default

%description license
license components for the colm package.


%package staticdev
Summary: staticdev components for the colm package.
Group: Default
Requires: colm-dev = %{version}-%{release}

%description staticdev
staticdev components for the colm package.


%prep
%setup -q -n colm-0.14.7
cd %{_builddir}/colm-0.14.7
%patch -P 1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1736468607
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%autogen
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1736468607
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/colm
cp %{_builddir}/colm-%{version}/COPYING %{buildroot}/usr/share/package-licenses/colm/18d0c1c269850a9f7731a4546df6b6e77bef0bfe || :
cp %{_builddir}/colm-%{version}/src/aapl/COPYING %{buildroot}/usr/share/package-licenses/colm/41723331b2592326d06ed97c53d9859c624e738b || :
export GOAMD64=v2
GOAMD64=v2
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/colm
/usr/bin/colm-wrap

%files data
%defattr(-,root,root,-)
/usr/share/ril.lm
/usr/share/rlhc-c.lm
/usr/share/rlhc-crack.lm
/usr/share/rlhc-csharp.lm
/usr/share/rlhc-d.lm
/usr/share/rlhc-go.lm
/usr/share/rlhc-java.lm
/usr/share/rlhc-js.lm
/usr/share/rlhc-julia.lm
/usr/share/rlhc-main.lm
/usr/share/rlhc-ocaml.lm
/usr/share/rlhc-ruby.lm
/usr/share/rlhc-rust.lm
/usr/share/runtests

%files dev
%defattr(-,root,root,-)
/usr/include/aapl/astring.h
/usr/include/aapl/avlbasic.h
/usr/include/aapl/avlcommon.h
/usr/include/aapl/avlibasic.h
/usr/include/aapl/avlikeyless.h
/usr/include/aapl/avlimap.h
/usr/include/aapl/avlimel.h
/usr/include/aapl/avlimelkey.h
/usr/include/aapl/avliset.h
/usr/include/aapl/avlitree.h
/usr/include/aapl/avlkeyless.h
/usr/include/aapl/avlmap.h
/usr/include/aapl/avlmel.h
/usr/include/aapl/avlmelkey.h
/usr/include/aapl/avlset.h
/usr/include/aapl/avltree.h
/usr/include/aapl/bstcommon.h
/usr/include/aapl/bstmap.h
/usr/include/aapl/bstset.h
/usr/include/aapl/bsttable.h
/usr/include/aapl/bubblesort.h
/usr/include/aapl/buffer.h
/usr/include/aapl/compare.h
/usr/include/aapl/dlcommon.h
/usr/include/aapl/dlist.h
/usr/include/aapl/dlistmel.h
/usr/include/aapl/dlistval.h
/usr/include/aapl/insertsort.h
/usr/include/aapl/mergesort.h
/usr/include/aapl/quicksort.h
/usr/include/aapl/resize.h
/usr/include/aapl/rope.h
/usr/include/aapl/sbstmap.h
/usr/include/aapl/sbstset.h
/usr/include/aapl/sbsttable.h
/usr/include/aapl/svector.h
/usr/include/aapl/table.h
/usr/include/aapl/vector.h
/usr/include/colm/bytecode.h
/usr/include/colm/colm.h
/usr/include/colm/colmex.h
/usr/include/colm/config.h
/usr/include/colm/debug.h
/usr/include/colm/defs.h
/usr/include/colm/input.h
/usr/include/colm/internal.h
/usr/include/colm/map.h
/usr/include/colm/pdarun.h
/usr/include/colm/pool.h
/usr/include/colm/program.h
/usr/include/colm/struct.h
/usr/include/colm/tree.h
/usr/include/colm/type.h
/usr/include/libfsm/action.h
/usr/include/libfsm/asm.h
/usr/include/libfsm/common.h
/usr/include/libfsm/dot.h
/usr/include/libfsm/fsmgraph.h
/usr/include/libfsm/gendata.h
/usr/include/libfsm/ragel.h
/usr/include/libfsm/redfsm.h
/usr/lib64/libcolm-0.14.7.so
/usr/lib64/libcolm.so
/usr/lib64/libfsm-0.14.7.so
/usr/lib64/libfsm.so

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/colm/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/colm/18d0c1c269850a9f7731a4546df6b6e77bef0bfe
/usr/share/package-licenses/colm/41723331b2592326d06ed97c53d9859c624e738b

%files staticdev
%defattr(-,root,root,-)
/usr/lib64/libcolm.a
/usr/lib64/libfsm.a
